config/routes.rb
Rails.application.routes.draw do
    resources :prospects
    devise_for :users
    
    root to: "pages#home" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
    validates :committeename, presence: true
    validates :contactemail, presence: true
    validates :user_id, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :prospects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_prospect, only: [:edit, :update, :show,:destroy]
    
    def index
       @prospects = Prospect.all 
    end
    
    def new
       @prospect = Prospect.new 
    end
    
    def create
       @prospect = Prospect.new(prospect_params) 
       
        if @prospect.save
            flash[:notice] = "Successfully saved prospect!"
            redirect_to prospects_path
        else
            render 'new'
        end
    end
    
    def show

    end
    
    def edit

    end    
    
    def update
        
        
        if @prospect.update(prospect_params)
            flash[:notice] = "Successfully saved prospect!"
            redirect_to prospects_path
        else
            render 'edit'
        end        
        
    end
    
    def destroy
        
        @prospect.destroy
        flash[:notice] = "Prospect was removed!"
        redirect_to prospects_path
    end
    
    private
    
    def set_prospect
        @prospect = Prospect.find(params[:id])
    end
    
    def prospect_params
       params.require(:prospect).permit(:committeename, :contactemail, :contactphone, :contactfirst, :contactlast, :contacttitle, :billingstreetone, :billingstreettwo, :billingcity, :billingstate, :billingzip, :committeeurl) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-black">
  <div class="container">
    <p class="m-0 text-center text-white small">All rights reserved. Ballot America Corp &copy; 2016-2019</p>
  </div>
  <!-- /.container -->
</footer>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballot America Partner Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mx-auto">
      <%= yield %>
      
      <% if current_page?(root_path) %>
          <%= render "layouts/footer", class: "footerb" %>
      <% else %>
      <% end %>  
    </div>
  </body>
</html>

app/views/pages/_main.html.erb
<div class="header-ui" id="main">
    <%= link_to "SIGN UP TO BECOME A PARTNER", new_user_registration_path, :class=>"btn btn-primary" %>
</div>

app/views/pages/_nav.html.erb
<!--Navbar -->
<nav class="navbar navbar-expand-lg navbar-white bg-white">
  <%= link_to image_tag("logo.png", size: "48"), root_path, class: 'navbar-brand d-inline-block align-top' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "What we do", root_path, class: "nav-link" %>
      </li>
      <% if current_user && user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class=>"btn btn-info" %>
          </li>          
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn-warning" %>
          </li>
        <% end %>  
        </div>
      </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->

app/views/pages/_need.html.erb
<div class="header-ui" id="need">
    <%= link_to "SIGN UP TO BECOME A PARTNER", new_user_registration_path, :class=>"btn btn-primary" %>
</div>

app/views/pages/_steps.html.erb
<div class="header-ui" id="steps">
    <%= link_to "SIGN UP TO BECOME A PARTNER", new_user_registration_path, :class=>"btn btn-primary" %>
</div>

app/views/pages/_why.html.erb
<div class="header-ui" id="why">
    <%= link_to "SIGN UP TO BECOME A PARTNER", new_user_registration_path, :class=>"btn btn-primary" %>
</div>

app/views/pages/home.html.erb
<%= render "pages/nav" %>
      <%= render "layouts/messages" %>
<%= render "pages/main" %>
<%= render "pages/steps" %>
<%= render "pages/why" %>
<%= render "pages/need" %>

app/views/prospects/_form.html.erb
<% if @prospect.errors.any? %>
    <p>The following errors prevented your prospect from saving:</p>
    <ul>
        <% @prospect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>

<% end %>

<%= form_for @prospect do |f| %>
<h2>Contact</h2>

<p>
    <%= f.label "Committee name" %>
    <%= f.text_field :committeename %>
</p>

<p>
    <%= f.label "Email" %>
    <%= f.text_field :contactemail %>
</p>

<p>
    <%= f.label "Phone" %>
    <%= f.text_field :contactphone %>
</p>

<p>
    <%= f.label "Contact" %>
    <%= f.text_field :contactfirst %> <br />
    <%= f.text_field :contactlast %>
</p>

<p>
    <%= f.label "Title" %>
    <%= f.text_field :contacttitle %>
</p>

<hr>

<h2>Billing</h2>

<p>
    <%= f.label "Address line 1 " %>
    <%= f.text_field :billingstreetone %>
</p>

<p>
    <%= f.label "Address line 2 " %>
    <%= f.text_field :billingstreettwo %>
</p>

<p>
    <%= f.label "City " %>
    <%= f.text_field :billingcity %>
</p>

<p>
    <%= f.label "State " %>
    <%= f.text_field :billingstate %>
</p>

<p>
    <%= f.label "Zip code " %>
    <%= f.text_field :billingzip %>
</p>

<hr>

<h3>More</h3>

<p>
    <%= f.label "Website " %>
    <%= f.text_field :committeeurl %>
</p>

<p>
    <%= f.submit "Save" %>
</p>

<% end %>

app/views/prospects/edit.html.erb
<h1>Edit a Prospect</h1>

<%= render "prospects/form" %>

<p>
    <%= link_to "Back to Prospects", prospects_path %>    
</p>

app/views/prospects/index.html.erb
<h1>Prospects</h1>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class=>"btn btn-info" %>

<p>
    <%= link_to "Add a Prospect", new_prospect_path %>
</p>

<table>
    <tr>
        <th>Committee Name</th>
        <th>Contact Name</th>
        <th>Email</th>
        <th>Phone</th>
    </tr>
    <% @prospects.each do |prospect| %>
        <tr>
            <td><%= prospect.committeename %></td>
            <td><%= prospect.contactfirst %> <%= prospect.contactlast %></td>
            <td><%= prospect.contactemail %></td>
            <td><%= prospect.contactphone %></td>
            <td><%= link_to "Edit", edit_prospect_path(prospect) %></td>
            <td><%= link_to "Delete", prospect_path(prospect), method: :delete, data: {confirm: "Are you sure you want to delete this prospect? This cannot be undone."} %></td>
        </tr>
    <% end %>
</table>

app/views/prospects/new.html.erb
<h1>Add a Prospect</h1>

<%= render "prospects/form" %>

<%= link_to "Back to Prospects", prospects_path %>

app/views/prospects/show.html.erb
<h1>Prospect Information</h1>

<p>
    Committee name: <%= @prospect.committeename %>
</p>

<p>
    Email: <%= @prospect.contactemail %>
</p>

<p>
    Phone: <%= @prospect.contactphone %>
</p>

<p>
    Contact: <%= @prospect.contactfirst %> <br />
    <%= @prospect.contactlast %>
</p>

<p>
    Title: <%= @prospect.contacttitle %>
</p>

<hr>

<h2>Billing</h2>

<p>
    Address line 1: <%= @prospect.billingstreetone %>
</p>

<p>
    Address line 2: <%= @prospect.billingstreettwo %>
</p>

<p>
    City: <%= @prospect.billingcity %>
</p>

<p>
    State: <%= @prospect.billingstate %>
</p>

<p>
    Zip code: <%= @prospect.billingzip %>
</p>

<hr>

<h2>More</h2>

<p>
    Website: <%= @prospect.committeeurl %>
</p>

<p>
    <%= link_to "Edit this Prospect", edit_prospect_path(@prospect) %> | <%= link_to "Back to Prospects", prospects_path %>    
</p>